# **NumPy**

## **0. Introduction**

### **0.1. Contents**

### **0.2. References**

This note draws heavily from the following sources:

- Chase Coleman, Spencer Lyon, and Jesse Perla. (n.d.). Introduction to Numpy. QuantEcon DataScience. [link](https://datascience.quantecon.org/scientific/numpy_arrays.html)
- Qingkai Kong, Timmy Siauw, and Alexandre Bayen. (2020). Python Programming and Numerical Methods : A Guide for Engineers and Scientists. Elsevier. [link](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html)

I would highly recommend checking them out if you are interested in learning more about this topic.

## **1. NumPy**

Now that we have learned the fundamentals of programming in Python, we will learn how we can use Python to perform the computations required in computational economics.

We call these the "scientific Python tools".

The foundational library that helps us perform these computations is known as `numpy`, which means numerical Python.

Before we get started, please note that the convention for importing the numpy package is to use the nickname `np`.

In [1]:
import numpy as np

### **1.1. Numpy Arrays**

Numpy's core contribution is a new data type called an **array**.

An array is similar to a list, but numpy imposes some additional restrictions on how the data inside is organized.

These restrictions allow numpy to
- be more efficient in performing mathematical and scientific computations;
- expose functions that allow numpy to do the necessary linear algebra for machine learning and statistics.

Then, what actually is an array?

An array is **a multi-dimensional grid of values**.

What does it mean?

It is easier to demonstrate than to explain.

In this block of code, we build a 1-dimensional array.

In [3]:
# Create a 1-dimensional array from a list.

arr_1d = np.array([1, 2, 3])

print(arr_1d)

[1 2 3]


You can think of a 1-dimensional array as a list of numbers.

In [4]:
# We can index like we did with lists.

print(arr_1d[0])   # Indexing
print(arr_1d[0:2]) # Slicing

1
[1 2]


Note that the range of indicies does not include the end-point, that is

In [6]:
print(arr_1d[0:3])
print(arr_1d[0:3] == arr_1d[:]) # You can index all values of the array by typing nothing before and after ':'.
print(arr_1d[0:2])

[1 2 3]
[ True  True  True]
[1 2]


The differences emerge as we move into higher dimensions.

Next, we define a 2-dimensional array (a matrix).

In [7]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Notice that the data is no longer represented as something flat, but rather, as three rows and three columns of numbers.

The first question is that you might ask yourself is: "How do I access the values in this array?"

You access each element by **specifying a row first and then a column**.

For example, if we wanted to access the `6` in `arr_2d`, we would ask for the (1, 2) element.

In [9]:
print(arr_2d[1, 2]) # Indexing into two dimensions.

6


Or to get the top left corner,

In [10]:
print(arr_2d[0, 0])

1


To get the first, and then second rows,

In [13]:
print(arr_2d[0, :]) # First row of arr_2d
print(arr_2d[1, :]) # Second row of arr_2d

[1 2 3]
[4 5 6]


Or the columns,

In [14]:
print(arr_2d[:, 0]) # First column of arr_2d
print(arr_2d[:, 1]) # Second column of arr_2d

[1 4 7]
[2 5 8]


This indexing and slicing in numpy array continues to generalize to the higher dimensions, since numpy gives us as many dimensions as we want in an array.

For example, we build a 3-dimensional array below.

In [15]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]])

print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


### **1.2. Array Indexing**